const Data = [

      {
    dateTime: "01 May, 2025 at 5pm",
    status: "Completed",
    type: "Offline",
    buyerName: "Mango Products Limited",
    brand: "Mango",
    dept: "Design",
    title: "Catalog Discussion with Zara",
    meetingDate: "01 May, 2025 at 5pm",
    participants: ["Mohit Sablekar"],
  },
  {
    dateTime: "03 May, 2025 at 2pm",
    status: "Upcoming",
    type: "Online",
    buyerName: "Cherry Innovations",
    brand: "Cherry",
    dept: "Development",
    title: "UI/UX review",
    meetingDate: "03 May, 2025 at 2pm",
    participants: ["Mohit Sablekar"],
  },
  {
    dateTime: "03 May, 2025 at 4pm",
    status: "Rescheduled",
    type: "Offline",
    buyerName: "Fincaps Inc.",
    brand: "Fincaps",
    dept: "Marketing",
    title: "Campaign Strategy",
    meetingDate: "04 May, 2025 at 4pm",
    participants: ["Mohit Sablekar"],
  },
  {
    dateTime: "03 May, 2025 at 4pm",
    status: "Follow Up",
    type: "Online",
    buyerName: "Protein Chips",
    brand: "Protein",
    dept: "Finance",
    title: "Budget Review",
    meetingDate: "TBD",
    participants: ["Mohit Sablekar"],
  },
  {
    dateTime: "03 May, 2025 at 5pm",
    status: "Overdue",
    type: "Offline",
    buyerName: "Banana Solutions",
    brand: "Banana",
    dept: "Product",
    title: "Product Prioritization",
    meetingDate: "03 May, 2025 at 5pm",
    participants: ["Mohit Sablekar"],
  },
  {
    dateTime: "03 May, 2025 at 5pm",
    status: "In Progress",
    type: "Offline",
    buyerName: "Coconut Group Co.",
    brand: "Coconut",
    dept: "Support",
    title: "Customer Feedback",
    meetingDate: "03 May, 2025 at 5pm",
    participants: ["Mohit Sablekar"],
  },
  {
    dateTime: "04 May, 2025 at 2pm",
    status: "Ongoing",
    type: "Online",
    buyerName: "Lemon Technologies",
    brand: "Lemon",
    dept: "Sales",
    title: "Sales Meeting",
    meetingDate: "04 May, 2025 at 2pm",
    participants: ["Mohit Sablekar"],
  },
  {
    dateTime: "04 May, 2025 at 3pm",
    status: "Completed",
    type: "Offline",
    buyerName: "Snapfruit Inc.",
    brand: "Snapfruit",
    dept: "Innovation",
    title: "Mobile Strategy",
    meetingDate: "04 May, 2025 at 3pm",
    participants: ["Mohit Sablekar"],
  },
  {
    dateTime: "04 May, 2025 at 4pm",
    status: "Draft",
    type: "Online",
    buyerName: "Grid Systems",
    brand: "Kitt",
    dept: "HR",
    title: "Employee Engagement",
    meetingDate: "04 May, 2025 at 4pm",
    participants: ["Mohit Sablekar"],
  },
  {
    dateTime: "05 May, 2025 at 5pm",
    status: "Archived",
    type: "Offline",
    buyerName: "Orange Enterprises",
    brand: "Orange",
    dept: "Legal",
    title: "Contract Review",
    meetingDate: "05 May, 2025 at 5pm",
    participants: ["Mohit Sablekar"],
  }

]

export default Data